### ISSUE TITLE
Travis build failing due to pinned flake8-import-order

### ISSUE THREAD

**Issue by hugovk** [jstasiak/python-zeroconf#92]
This has started failing PRs. 

Here's from a build that's the same as latest master:
```
$ make flake8
flake8 --max-line-length=110 examples *.py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/main/application.py", line 322, in run
    self._run(argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/main/application.py", line 305, in _run
    self.initialize(argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/main/application.py", line 296, in initialize
    self.register_plugin_options()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/main/application.py", line 154, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/plugins/manager.py", line 488, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/plugins/manager.py", line 284, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/plugins/manager.py", line 484, in register_and_enable
    call_register_options(plugin)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/plugins/manager.py", line 380, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/plugins/manager.py", line 230, in register_options
    add_options(optmanager)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8_import_order/flake8_linter.py", line 29, in add_options
    parser.config_options.append("application-import-names")
AttributeError: 'OptionManager' object has no attribute 'config_options'
make: *** [flake8] Error 1
```
https://travis-ci.org/hugovk/python-zeroconf/builds/179008513

flake8-import-order <0.6.0 doesn't work with flake8 3.0: https://github.com/PyCQA/flake8-import-order/issues/79

Quick fix is to pin flake8. Proper fix is to unpin both, decide on a style and set that for flake8-import-order.

**Comment by hugovk** [comment]
Fixed by https://github.com/jstasiak/python-zeroconf/pull/93.
