### ISSUE TITLE
IPv6 sending without scope is broken in tests

### ISSUE THREAD

**Issue by bdraco** [jstasiak/python-zeroconf#817]
Regressed in #343

```
DEBUG    zeroconf:_core.py:667 Sending to (None, 5353) (34 bytes #1) <DNSOutgoing:{multicast=True, flags=0, questions=[ptr[question,QM,in,_http._tcp.local.]], answers=[], authorities=[], additionals=[]}> as b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x05_http\x04_tcp\x05local\x00\x00\x0c\x00\x01'...
DEBUG    zeroconf:_logger.py:47 Error sending through socket 16
Traceback (most recent call last):
  File "/Users/runner/work/python-zeroconf/python-zeroconf/zeroconf/_core.py", line 680, in async_send
    transport.sendto(packet, (real_addr, port or _MDNS_PORT, *v6_flow_scope))
TypeError: 'NoneType' object is not iterable
```
